# Generated by Django 6.0.1 on 2026-01-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('value_sale', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Ventas diarias',
                'verbose_name_plural': 'Ventas diarias',
                'db_table': 'ventas_diarias',
            },
        ),
    ]
