# Generated by Django 5.2.5 on 2026-01-08 23:05

from datetime import date
from decimal import Decimal

from django.db import migrations


def create_mock_data(apps, schema_editor):
    DailySales = apps.get_model('dashboard', 'DailySales')
    DailySales.objects.bulk_create([
        DailySales(date=date(2025, 1, 1), client_id='C001', product='Laptop', value_sale=Decimal('1200.00')),
        DailySales(date=date(2025, 2, 2), client_id='C002', product='Mouse', value_sale=Decimal('25.50')),
        DailySales(date=date(2025, 2, 3), client_id='C001', product='Keyboard', value_sale=Decimal('79.99')),
        DailySales(date=date(2025, 1, 4), client_id='C003', product='Monitor', value_sale=Decimal('299.00')),
        DailySales(date=date(2025, 1, 5), client_id='C004', product='Dock', value_sale=Decimal('149.99')),
        DailySales(date=date(2025, 2, 5), client_id='C004', product='Dock', value_sale=Decimal('149.99')),
        DailySales(date=date(2025, 3, 5), client_id='C005', product='Dock', value_sale=Decimal('149.99')),
        DailySales(date=date(2025, 1, 5), client_id='C006', product='Dock', value_sale=Decimal('149.99')),
        DailySales(date=date(2025, 1, 5), client_id='C004', product='Dock', value_sale=Decimal('149.99')),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_mock_data, migrations.RunPython.noop),
    ]
